"""empty message

Revision ID: 0697265799f2
Revises: 67168ab4efaa
Create Date: 2019-09-11 23:49:27.582749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0697265799f2'
down_revision = '67168ab4efaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('listings', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.add_column('users', sa.Column('session_key', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'users', ['session_key'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'session_key')
    op.alter_column('listings', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('listings', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
