"""empty message

Revision ID: 67168ab4efaa
Revises: d018d799acf7
Create Date: 2019-07-19 12:26:57.013800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67168ab4efaa'
down_revision = 'd018d799acf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
