"""empty message

Revision ID: f75116b58925
Revises: 0697265799f2
Create Date: 2019-09-13 22:22:57.849897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75116b58925'
down_revision = '0697265799f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'listings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'user_id')
    # ### end Alembic commands ###
